# ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
# │  used properties are included. For a list of all supported properties and their functions,     │
# │  see: https://fshschool.org/docs/sushi/configuration/.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.uv.vulcan-rwd
canonical: http://hl7.org/fhir/uv/vulcan-rwd
name: VulcanRWD
title: Vulcan Real World Data FHIR Implementation Guide
description: A FHIR Implementation Guide that provides profiles and use cases that show how real world data can be exposed in such a way that it can be used for research purposes.
status: draft # draft | active | retired | unknown
version: 0.1.0
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2022+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#001 "World" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: HL7 International - Biomedical Research & Regulation Work Group
  url: http://hl7.org/Special/committees/rcrim
  # email: test@example.org

dependencies:
  hl7.fhir.uv.ips: 1.0.0


pages:
  index.md:
    title: Home
  usecases.md:
    title: Use Cases

menu:
  Home: index.html
  Use Cases: usecases.html
  Artifacts: artifacts.html
